
title: "Columbia University Digital Humanities"
desctiption: Digital Humanities at Columbia University
url: 
permalink: ':title/'

markdown: kramdown
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:path.html
    title: projects
  people:
    output: true
    permalink: /people/:path.html
    title: people
  teams:
    output: true
    permalink: /teams/:path.html
    title: teams

sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: 

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
exclude: [vendor]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag]